#!/bin/bash

REPORT=SUPPORTED_VERSIONS.MD

check() {
    local ruby_version=$1
    local puppet_version=$2

    report_string="ruby_version=$ruby_version puppet_version=$puppet_version"

    echo "==> Running ${report_string}"

    export PUPPET_VERSION=$puppet_version
    rm -f Gemfile.lock
    rbenv global $ruby_version

    bundle -h 2>&1 1>/dev/null
    if [ $? -ne 0 ]; then
      gem install bundler
    fi

    bundle install
    bundle exec rake test

    if [ $? -ne 0 ]; then
        echo "|${ruby_version}|${puppet_version}|FAILED|" >> $REPORT
    else
        echo "|${ruby_version}|${puppet_version}|**SUPPORTED**|" >> $REPORT
    fi
}

unsupported() {
    local ruby_version=$1
    local puppet_version=$2

    echo "|${ruby_version}|${puppet_version}|UNSUPPORTED|" >> $REPORT
}

echo -e "| Ruby Version | Puppet Version | Status |\n|---|---|---|" > $REPORT

if [ $# -gt 0 ]; then
  check $*
else
  check 1.8.7-p374 3.0.2
  check 1.8.7-p374 3.7.3
  unsupported 1.8.7-p374 4.0.0
  unsupported 1.8.7-p374 4.1.0

  check 1.9.3-p551 3.0.2
  check 1.9.3-p551 3.7.3
  check 1.9.3-p551 4.0.0
  check 1.9.3-p551 4.1.0
fi

echo "*generated at `date`*" >> $REPORT

cat $REPORT
